//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class State {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal State() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonSearch.Resources.State", typeof(State).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hampshire.
        /// </summary>
        public static string NewHampshire {
            get {
                return ResourceManager.GetString("NewHampshire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Jersey.
        /// </summary>
        public static string NewJersey {
            get {
                return ResourceManager.GetString("NewJersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mexico.
        /// </summary>
        public static string NewMexico {
            get {
                return ResourceManager.GetString("NewMexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York.
        /// </summary>
        public static string NewYork {
            get {
                return ResourceManager.GetString("NewYork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Carolina.
        /// </summary>
        public static string NorthCarolina {
            get {
                return ResourceManager.GetString("NorthCarolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Dakota.
        /// </summary>
        public static string NorthDakota {
            get {
                return ResourceManager.GetString("NorthDakota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhode Island.
        /// </summary>
        public static string RhodeIsland {
            get {
                return ResourceManager.GetString("RhodeIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Carolina.
        /// </summary>
        public static string SouthCarolina {
            get {
                return ResourceManager.GetString("SouthCarolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Dakota.
        /// </summary>
        public static string SouthDakota {
            get {
                return ResourceManager.GetString("SouthDakota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Virginia.
        /// </summary>
        public static string WestVirginia {
            get {
                return ResourceManager.GetString("WestVirginia", resourceCulture);
            }
        }
    }
}
